### ISSUE TITLE
support githubs flavor of semver

### ISSUE THREAD

**Issue by maxogden** [johnmuhl/electron-prebuilt-updater#2]
today `npm install electron-prebuilt -g` ended up installing a version of electron that was 674 commits old because they pushed out a release `v0.30.7` that overwrote the previously newest release `v0.33.1`

I think the version numbers they use for their releases have two major differences from semver:

- they don't increment the minor when adding new features (e.g. https://github.com/atom/electron/releases/tag/v0.31.2 should have been 0.32.0 because of the new APIs)
- they view each minor version (e.g. `0.31`, `0.32`) as a separate 'release channel', meaning if 0.33 is already out, they expect to be able to publish to 0.32 without affecting the latest version. this lets them do patch versions to fix tiny bugs in old electrons that atom is using so they can update quickly in atom without having to port atom to use the latest electron.

since these break the expectations of semver and npm, we need to do extra work here to make sure we publish electon versions in the right way:

- when doing a release, check the last release on npm. if the new version is higher than the old version, we can just do a publish as normal. however, is the new version is lower than the old version, we have to do prevent npm from publishing the `latest` tag, which is npms default

we fixed the issue today manually by running `npm tag electron-prebuilt@0.33.1 latest` which set the previous release as latest

cc @mafintosh @jlord

**Comment by kevinsawicki** [comment]
> since these break the expectations of semver and npm

So looking ahead a bit, if we have electron `1.x` and `2.x` channels out and we need to commit something to `1.x` only. Does the tag date of the `1.x` release being **later** than the tag date of the latest `2.x` release break any expectations of semver and npm?

**Comment by johnmuhl** [comment]
@maxogden is there anyway to publish a non-latest version? Is it ok to abuse tags for this; e.g. `npm publish electron-prebuilt --tag release` or something?

**Comment by maxogden** [comment]
that's not a common workflow people use npm for so npm doesn't really have
a concept of release channels, the workaround to support it is to
explicitly set the 'latest' version afterwards so that people don't get old
versions when they npm install

it might be worth opening an issue on npm to not autottag latest for lower
semver publishes, but the easier thing IMO is for us to directly agree on
publish semantics and not have to change the way npm works

On Thursday, September 24, 2015, Kevin Sawicki <notifications@github.com>
wrote:

> since these break the expectations of semver and npm
>
> So looking ahead a bit, if we have electron 1.x and 2.x channels out and
> we need to commit something to 1.x only. Does the tag date of the 1.x
> release being *later* than the tag date of the latest 2.x release break
> any expectations of semver and npm?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/johnmuhl/electron-prebuilt-updater/issues/2#issuecomment-142997703>
> .
>


-- 
Sent from my phone

**Comment by maxogden** [comment]
@johnmuhl i'm not sure... we just need to disable the `latest` tag from getting set. here are the ways i can think of:

- mark something else as `latest` as a separate api afterwards (non atomic but probably fine)
- figure out if theres a way to disable `latest` in the npm options (didn't see it in the docs but there may be a way)

**Comment by maxogden** [comment]
WOOT! thanks @johnmuhl 

@kevinsawicki so this hopefully shouldn't happen again in the future now. would be nice if electron switched to npm compatible semver at some point though just to prevent other potential weird situations and keep things nice and simple

**Comment by maxbrunsfeld** [comment]
> would be nice if electron switched to npm compatible semver at some point though just to prevent other potential weird situations and keep things nice and simple

I don't think electron is doing anything incompatible with semver by publishing patches for older versions. Continuing to maintain older versions is good.

The problem is that npm's `latest` tag has nothing whatsoever to do with semver. It just marks the version that was most recently uploaded. Background:
* https://github.com/npm/npm/issues/3397
* https://github.com/npm/npm/issues/4709
* https://github.com/npm/npm/issues/6778

It looks like the current workaround is to use `publishConfig` in the `package.json` to prevent `latest` being tagged.

**Comment by maxogden** [comment]
@maxbrunsfeld sorry, was not saying the `latest` tag thing is related to the semver spec, I was just referring to my first bullet point in the original post in this issue. currently the version numbers in electron aren't following the semver spec

**Comment by maxbrunsfeld** [comment]
Got it. The spec does say that for 0.x.x (the 'initial development' phase) anything goes, but I agree that pretty soon it would probably make sense to take Electron to 1.0, at which point it would be good to follow the normal semver stuff.

**Comment by maxogden** [comment]
@maxbrunsfeld oh yea that would be awesome

**Comment by johnmuhl** [comment]
Damn it. Looks like the workaround didn't work…

@maxogden is there anything useful in the Heroku logs about why re-tagging the latest might have failed?

**Comment by maxogden** [comment]
Sorry it's because I messed up the heroku redeploy of the new version. I
didn't notice my heroku credentials were stale yesterday. I just redeployed
it, master is live now
